image: node:latest

variables:
  PAGES_BRANCH: master

stages:
  - make_dev
  - pages

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

make_dev:
  stage: make_dev
  script: npm run-script ci-dev
  artifacts:
    paths:
      - dev

pages:
  stage: pages
  script:
    - mkdir public
    - cp -r dev "public/${CI_COMMIT_REF_SLUG}"
  cache:
    paths:
      -public/
  artifacts:
    paths:
      - public/${CI_COMMIT_REF_SLUG}
