image: node:latest

variables:
  PAGES_BRANCH: master

stages:
  - make_dev
  - copy_pages

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

make_dev:
  stage: make_dev
  only:
    - master
  script: npm run-script ci-dev
  artifacts:
    paths:
      - dev/

pages:
  stage: copy_pages
  rules:
    - if: '$CI_COMMIT_REF_NAME == $PAGES_BRANCH'
      when: always
    - when: manual
  script:
    - cp -r dev public
  artifacts:
    paths:
      - public
