image: node:latest

stages:
  - make_dev
  - copy_pages

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

make_dev:
  stage: make_dev
  only:
    - master
  script: npm run-script ci-dev
  artifacts:
    paths:
      - dev/

copy_pages:
  stage: copy_pages
  only:
    - master
  script:
    - cp -r dev public
  artifacts:
    paths:
      - public