 image: node:latest

    stages:
      - install
      - dev

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: install
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    main_build:
      stage: dev
      script: npm dev